1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np 

v = np.array([1,2,3,4,5,6,7,8,9,10])

print(v)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [6]:
m = np.array([[0,0,0],[0,0,0],[0,0,0]])

print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [7]:
m = np.array([[2,4,7,6,8],[8,7,2,1,9],[8,5,4,7,3],[1,4,7,8,5],[3,9,6,8,5]])

print(m)

[[2 4 7 6 8]
 [8 7 2 1 9]
 [8 5 4 7 3]
 [1 4 7 8 5]
 [3 9 6 8 5]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [3]:
m = np.array([[0,0,1,0],[1,0,1,0],[1,1,0,1],[1,0,0,1]])

print(m)

[[0 0 1 0]
 [1 0 1 0]
 [1 1 0 1]
 [1 0 0 1]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [4]:
v1 = np.array([3,7,4,8,6])
v2 = np.array([9,1,3,2,5])

print(v1 + v2)
print(v1 - v2)
print(v1 * v2)

[12  8  7 10 11]
[-6  6  1  6  1]
[27  7 12 16 30]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [5]:
v1 = np.array([3,7,4,8,6,9,1])
v2 = np.array([9,1,3,2,5,7,6])

print(np.dot(v1, v2)) 

161


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [9]:
m1 = np.array([[2,7],[4,6]])
m2 = np.array([[8,2,7],[2,3,3]])

print(np.dot(m1, m2))

[[30 25 35]
 [44 26 46]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [12]:
m = np.array([[8,2,7],[2,3,3],[6,7,4]])

print(np.linalg.inv(m))

[[ 0.1125 -0.5125  0.1875]
 [-0.125   0.125   0.125 ]
 [ 0.05    0.55   -0.25  ]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [13]:
m = np.array([[2,4,7,6],[8,7,2,1],[8,5,4,7],[1,4,7,8]])

mt = m.T
print(mt)

[[2 8 8 1]
 [4 7 5 4]
 [7 2 4 7]
 [6 1 7 8]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [17]:
m = np.array([[2,4,7,6],[8,7,2,1],[8,5,4,7]])
v = np.array([5,3,9,7])

print(np.dot(m, v))

[127  86 140]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [18]:
m = np.array([[0,1,0],[1,0,0]])
v = np.array([1,0,1])

print(np.dot(m, v))

[0 1]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [19]:
m1 = np.array([[2,7],[4,6]])
m2 = np.array([[5,4],[1,8]])

print(m1 * m2)

[[10 28]
 [ 4 48]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [20]:
m1 = np.array([[2,7],[4,6]])
m2 = np.array([[5,4],[1,8]])

print(np.dot(m1, m2))

[[17 64]
 [26 64]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [24]:
m = np.array([[3,71,4,84,6],[3,78,44,87,60],[32,27,4,8,76],[3,73,4,81,74],[3,27,42,8,62]])

print(m.sum())

964


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [25]:
m1 = np.array([[9,4,7,6],[8,7,2,1],[8,5,4,7],[9,4,8,8]])
m2 = np.array([[2,2,3,6],[4,2,2,1],[7,3,2,4],[1,4,1,2]])

print(m1 - m2)

[[7 2 4 0]
 [4 5 0 0]
 [1 2 2 3]
 [8 0 7 6]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [30]:
m = np.array([[0,0,1],[1,1,0],[0,1,0]])

print(m.sum(axis=1).reshape(-1,1))

[[1]
 [2]
 [1]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [33]:
m = np.array([[9,4,7,6],[8,7,2,1],[8,5,4,7]])

print(m * m)

[[81 16 49 36]
 [64 49  4  1]
 [64 25 16 49]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [34]:
v = np.array([19,4,17,46])

print(v * v)

[ 361   16  289 2116]
