1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np 

v = np.array([1,2,3,4,5,6,7,8,9,10])

print(v)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [6]:
m = np.array([[0,0,0],[0,0,0],[0,0,0]])

print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [10]:
m = np.random.randint(1, 11, (5, 5))

print(m)

[[ 2  9  6  3  6]
 [ 4  2  7  3  3]
 [ 9  1 10  4  3]
 [10 10  7  8  3]
 [ 5  7  6  6  4]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [11]:
m = np.random.rand(4, 4)

print(m)

[[0.4269057  0.18670535 0.10274641 0.17029742]
 [0.75424351 0.03198707 0.23990806 0.96619412]
 [0.54181046 0.47737414 0.49668715 0.71192445]
 [0.80572814 0.98014547 0.69904951 0.94466218]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [23]:
v1 = np.random.randint(1, 11, 5)
v2 = np.random.randint(1, 11, 5)

print(v1)
print(v2)
print(v1 + v2)
print(v1 - v2)
print(v1 * v2)

[ 5  7  8  2 10]
[ 5  9  7  7 10]
[10 16 15  9 20]
[ 0 -2  1 -5  0]
[ 25  63  56  14 100]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [22]:
v1 = np.random.rand(7)
v2 = np.random.rand(7)

print(v1)
print(v2)
print(np.dot(v1, v2)) 

[0.86493059 0.9360718  0.2956391  0.34483891 0.55003094 0.41406006
 0.04419081]
[0.40741816 0.80030426 0.50195946 0.34336446 0.99003728 0.21825931
 0.85775536]
2.0411634668862972


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [21]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 3))

print(m1)
print(m2)
print(np.dot(m1, m2))

[[1 7]
 [9 7]]
[[2 6 8]
 [1 2 4]]
[[  9  20  36]
 [ 25  68 100]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [19]:
m = np.random.randint(1, 11, (3, 3))

print(m)
print(np.linalg.inv(m))

[[10 10 10]
 [ 7  9  2]
 [ 1  1  6]]
[[ 0.52 -0.5  -0.7 ]
 [-0.4   0.5   0.5 ]
 [-0.02  0.    0.2 ]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [18]:
m = np.random.rand(4, 4)

mt = m.T
print(m)
print(mt)

[[0.86481749 0.54064707 0.73068534 0.21209974]
 [0.02378867 0.89290521 0.7153979  0.98458335]
 [0.82543048 0.68753962 0.65442142 0.99422193]
 [0.19702273 0.07663579 0.67074998 0.33739039]]
[[0.86481749 0.02378867 0.82543048 0.19702273]
 [0.54064707 0.89290521 0.68753962 0.07663579]
 [0.73068534 0.7153979  0.65442142 0.67074998]
 [0.21209974 0.98458335 0.99422193 0.33739039]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [24]:
m = np.random.randint(1, 11, (3, 4))
v = np.random.randint(1, 11, 4)

print(m)
print(v)
print(np.dot(m, v))

[[ 9  3  6  6]
 [ 4  7 10  3]
 [ 8  2  1  2]]
[ 6 10 10 10]
[204 224  98]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [25]:
m = np.random.rand(2, 3)
v = np.random.rand(3)

print(m)
print(v)
print(np.dot(m, v))

[[0.46424583 0.31128087 0.88931469]
 [0.0775004  0.00240587 0.94826017]]
[0.28836992 0.48912806 0.54149853]
[0.76769333 0.53700705]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [27]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 2))

print(m1)
print(m2)
print(m1 * m2)

[[10  4]
 [ 4  3]]
[[2 4]
 [3 8]]
[[20 16]
 [12 24]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [28]:
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 2))

print(m1)
print(m2)
print(np.dot(m1, m2))

[[3 9]
 [4 5]]
[[6 9]
 [2 2]]
[[36 45]
 [34 46]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [32]:
m = m1 = np.random.randint(1, 101, (5, 5))

print(m)
print(m.sum())

[[23 31 10 93 44]
 [15 17 81 65 64]
 [20 25 44 22 73]
 [81 47 33 62 34]
 [99  1 83 19 78]]
1164


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [33]:
m1 = np.random.randint(1, 11, (4, 4))
m2 = np.random.randint(1, 11, (4, 4))

print(m1)
print(m2)
print(m1 - m2)

[[ 2  9  8  8]
 [ 8  9  4  3]
 [ 8  2  2  6]
 [ 3  9  9 10]]
[[10  3  5  7]
 [ 8  5 10 10]
 [ 1  8  1  3]
 [ 2  3  7  8]]
[[-8  6  3  1]
 [ 0  4 -6 -7]
 [ 7 -6  1  3]
 [ 1  6  2  2]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [34]:
m = np.random.rand(3, 3)

print(m)
print(m.sum(axis=1).reshape(-1,1))

[[0.26946527 0.10457663 0.74792719]
 [0.75292031 0.96183801 0.16947506]
 [0.25924869 0.3148806  0.89966052]]
[[1.12196909]
 [1.88423338]
 [1.47378981]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [36]:
m = np.random.randint(1, 11, (3, 4))

print(m)
print(np.square(m))

[[4 7 2 7]
 [7 9 4 7]
 [4 5 3 4]]
[[16 49  4 49]
 [49 81 16 49]
 [16 25  9 16]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [34]:
v = np.random.randint(1, 51, 4)

print(v * v)

[ 361   16  289 2116]
